# This file defines the CI for running on LLNL CZ and RZ machines.
# Currently only runs on Toss machines.  BlueOS will be enabled next.

before_script:
  - echo "Before script section"
  - python2 -V  # Print out python version for debugging
  - python3 -V  # Print out python version for debugging

after_script:
  - echo "After script section"

build_and_test_cz:
  extends: 
    - .cz_job
    - .build_and_test_script

# Templates
.build_and_test_script:
  stage: build
  script:
#     Build and test blt
    - gitlab/scripts/build_and_test.sh > buildandtest.txt
  artifacts:
    paths:
     - buildandtest.txt
    reports:
      junit: 
        - build_*/junit.xml 

.cz_job:
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -p pdebug"
  tags:
    - quartz
    - shell
  rules:
    - if: '$LC_ZONE == "CZ"' # run only if ...
